services:
  ollama:
    volumes:
      - /home/nic/docker-volume-data/ollama/ollama:/root/.ollama
    container_name: ollama
    # pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - phantomlink
networks:
  phantomlink:
    external: true
# NOTE: not doing TS for my containers right now
# ollama-ts:
#   volumes:
#     - /home/nic/docker-volume-data/ollama/ollama:/root/.ollama
#     - /home/nic/docker-volume-data/ollama/tailscale:/var/lib/tailscale
#   container_name: ollama-ts
#   # pull_policy: always
#   tty: true
#   restart: unless-stopped
#   image: ollama/ollama:latest
#   network_mode: service:ts-ollama
#   # ports:
#   #   - 7869:11434
#   environment:
#     - OLLAMA_KEEP_ALIVE=24h
#     - OLLAMA_HOST=0.0.0.0
#   env_file: .env
#   deploy:
#     resources:
#       reservations:
#         devices:
#           - driver: nvidia
#             count: 1
#             capabilities: [gpu]
#
# ts-ollama:
#   image: tailscale/tailscale:latest
#   hostname: ollama
#   environment:
#     - TS_STATE_DIR=/var/lib/tailscale
#   volumes:
#     - /home/nic/docker-volume-data/ollama/data/tailscale:/var/lib/tailscale
#   devices:
#     - /dev/net/tun:/dev/net/tun
#   cap_add:
#     - net_admin
#     - sys_module
#   restart: unless-stopped
