services:
  kotaemon:
    image: ghcr.io/cinnamon/kotaemon:main-full
    volumes:
      - ./data:/app/ktem_app_data
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7862:7860"
    env_file: .env
    networks:
      - phantomlink
networks:
  phantomlink:
    external: true
