services:
  whisper_asr_webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    volumes:
      - /tmp:/tmp
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    ports:
      - "9099:9000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
