services:
  glances:
    image: "nicolargo/glances:latest"
    container_name: "glances"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
    pid: "host"
    ports:
      - "61208:61208"
      - "61209:61209"
    environment:
      GLANCES_OPT: -w
    security_opt:
      - "apparmor:unconfined"
    deploy:
      resources:
        limits:
          memory: "1g"
    networks:
      - visibility_network
    restart: unless-stopped
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: "babyblue-aurora"
    ports:
      - "19999:19999"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      PGID: "953"  # getent group docker | cut -d: -f3
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - visibility_network
    deploy:
      resources:
        limits:
          memory: "1g"

networks:
  # Custom network for the ARR suite services
  visibility_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.70.0.0/16
