services:
  minio:
    container_name: "minio"
    image: "minio/minio:RELEASE.2025-04-03T14-56-28Z"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - "/tank/encrypted/docker/minio-zfs/data:/data:rw"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "4g"
    networks:
      - phantomlink
    labels:
      traefik.enable: "true"

      # Console UI
      traefik.http.routers.minio-console.rule: Host(`minio.paynepride.com`)
      traefik.http.routers.minio-console.tls.certresolver: letsencrypt
      traefik.http.routers.minio-console.tls.domains[0].main: "paynepride.com"
      traefik.http.routers.minio-console.tls.domains[0].sans: "*.paynepride.com"
      traefik.http.services.minio-console-svc.loadbalancer.server.port: 9001
      traefik.http.routers.minio-console.middlewares: default-whitelist@file
      traefik.http.routers.minio-console.service: minio-console-svc

      # S3 API
      traefik.http.routers.minio-api.rule: Host(`s3.paynepride.com`)
      traefik.http.routers.minio-api.tls.certresolver: letsencrypt
      traefik.http.routers.minio-api.tls.domains[0].main: "paynepride.com"
      traefik.http.routers.minio-api.tls.domains[0].sans: "*.paynepride.com"
      traefik.http.services.minio-api-svc.loadbalancer.server.port: 9000
      # traefik.http.routers.minio-api.middlewares: default-whitelist@file
      traefik.http.routers.minio-api.service: minio-api-svc

networks:
  phantomlink:
    external: true
