services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /tank/encrypted/docker/karakeep-zfs/data:/data
    ports:
      - 3030:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      OLLAMA_BASE_URL: http://100.89.224.92:11434
      OLLAMA_INFERENCE_TEXT_MODEL: qwen2:7b-instruct-q5_K_M
      INFERENCE_TEXT_MODEL: qwen2:7b-instruct-q5_K_M
      INFERENCE_IMAGE_MODEL: llava:13b

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
    networks:
      - phantomlink
    labels:
      traefik.enable: "true"
      traefik.http.routers.karakeep.rule: "Host(`karakeep.paynepride.com`)"
      traefik.http.routers.karakeep.tls.certresolver: letsencrypt
      traefik.http.routers.karakeep.tls.domains[0].main: "paynepride.com"
      traefik.http.routers.karakeep.tls.domains[0].sans: "*.paynepride.com"
      traefik.http.services.karakeep.loadbalancer.server.port: 3000
      # traefik.http.routers.karakeep.middlewares: default-whitelist@file
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - phantomlink
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      # - meilisearch:/meili_data
      - /tank/encrypted/docker/karakeep-zfs/meilsearch:/meili_data
    networks:
      - phantomlink

networks:
  phantomlink:
    external: true
