services:
  nitter:
    image: ghcr.io/sekai-soft/nitter-self-contained
    container_name: nitter
    ports:
      - "0.0.0.0:8889:8081"
    volumes:
      - nitter-data:/nitter-data
      - /tank/encrypted/docker/nitter/twitter-credentials.json:/nitter-data/twitter-credentials.json
      - /tank/encrypted/docker/nitter/nitter.conf:/src/nitter.conf
      # - ./data/personas/Default:/data/personas/Default
    depends_on:
      nitter-redis:
        condition: service_healthy
    environment:
      - NITTER_ACCOUNTS_FILE=/nitter-data/guest_accounts.json
      - DISABLE_REDIS=1
      - REDIS_HOST=nitter-redis
      - TWITTER_CREDENTIALS_FILE=/nitter-data/twitter-credentials.json
    # - USE_CUSTOM_CONF=1
      # optional instance custmizations from env
      - INSTANCE_TITLE=Custom title
      - INSTANCE_THEME=Twitter Dark
      - INSTANCE_INFINITE_SCROLL=1
      - INSTANCE_BASE64_MEDIA=1
      - INSTANCE_HOSTNAME=localhost:8081
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: wget -nv --tries=1 --spider http://0.0.0.0:8081 || exit 1
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - phantomlink
    labels:
      traefik.enable: "true"
      traefik.http.routers.nitter.rule: "Host(`nitter.paynepride.com`)"
      traefik.http.routers.nitter.tls.certresolver: letsencrypt
      traefik.http.routers.nitter.tls.domains[0].main: "paynepride.com"
      traefik.http.routers.nitter.tls.domains[0].sans: "*.paynepride.com"
      traefik.http.routers.nitter.middlewares: default-whitelist@file
      traefik.http.services.nitter.loadbalancer.server.port: 8081
  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    networks:
      - phantomlink
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 12
volumes:
  nitter-data:
  nitter-redis:

networks:
  phantomlink:
    external: true
