services:
  freshrss:
    image: freshrss/freshrss:latest
    # # Optional build section if you want to build the image locally:
    # build:
    #   # Pick #latest (slow releases) or #edge (rolling release) or a specific release like #1.21.0
    #   context: https://github.com/FreshRSS/FreshRSS.git#latest
    #   dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - /tank/encrypted/docker/freshrss-zfs/data:/var/www/FreshRSS/data
      - /tank/encrypted/docker/freshrss-zfs/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/Chicago
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16 10.0.0.1/8 100.64.0.0/10
      PUBLISHED_PORT: 8080
    ports:
      - 8092:80
    networks:
      - phantomlink
networks:
  phantomlink:
    external: true
