services:
  kanboard:
    container_name: kanboard-new
    image: kanboard/kanboard:latest
    ports:
      - "8009:80"
      - "4439:443"
    env_file: .env
    environment:
      - TZ="America/Chicago"
      - PUID="1000"
      - PGID="1000"
      - PLUGIN_INSTALLER=true
    volumes:
      - /tank/encrypted/docker/kanboard/data:/var/www/app/data
      - /tank/encrypted/docker/kanboard/plugins:/var/www/app/plugins
      - /tank/encrypted/docker/kanboard/ssl:/etc/nginx/ssl
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.kanboard.rule: "Host(`kanboard.paynepride.com`)"
      traefik.http.routers.kanboard.tls.certresolver: "letsencrypt"
      traefik.http.routers.kanboard.tls.domains[0].main: "paynepride.com"
      traefik.http.routers.kanboard.tls.domains[0].sans: "*.paynepride.com"
      traefik.http.services.kanboard.loadbalancer.server.port: "80"
      # traefik.http.routers.kanboard.middlewares: default-whitelist@file
    networks:
      - phantomlink
networks:
  phantomlink:
    external: true
